language: cpp

sudo: false

dist: trusty

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Deps/conda

before_install:
  # Dependencies are downloaded in $HOME/Downloads and installed in $HOME/Deps
  - mkdir -p $HOME/Downloads $HOME/Deps

install:
  - ./dependencies/travis/anaconda.sh

before_script:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - test -n $FC && unset FC

script:
  - ./custom.sh build_$(date "+%Y-%m-%d-%H-%M-%S")
