package:
  name: conda-example-hybrid
  version: "0.0.0"

source:
  path: ../  # this can be changed to git-url

build:
  number: 0
  script:
    - cmake -H. -Bbuild_conda -G "${CMAKE_GENERATOR}" -DCMAKE_INSTALL_PREFIX=${PREFIX}         
    - cmake --build build_conda --target install

requirements:
  build:
    - cmake >=3.9
    - {{ compiler('cxx') }}
    - mkl-devel
    - openmpi
  run:
    - mkl-devel
    - openmpi

about:
  home: http://www.example.com
  license: MIT
  summary: "Summary in here ..."
